

CREATE    TABLE    MEORIENTB2B_BI.ADDED_RFQ_MATCH_DATA( 
 RFQ_ID  VARCHAR(50),
 RFQ_WEBSITE_ID VARCHAR(50),
	SUPPLIER_WEBSITE_ID  VARCHAR(50),
	SUPPLIER_ID VARCHAR(50),
	MATCH_SCORE FLOAT,
	TAG_CODE VARCHAR(50),
	TAG_NAME VARCHAR(100),
	OP_TIME  NUMERIC,
	ACTION_TIME  DATE,
	CREATE_TIME  DATE,
	SOURCE VARCHAR(50)
			)