

SELECT DISTINCT
EM.country_name,
bb.purchaser_id,
ebi.email,
PPIT.TAG_CODE,
swc.WEBSITE_ID,
EBL.ACTION_TIME,
EBL.ACTION_TYPE 
FROM
 MEORIENTB2B_PRD.EM_BADGE_ACTION_LOG ebl
 LEFT JOIN MEORIENTB2B_PRD.EM_BADGE_INFO ebi ON EBI.id = EBL.BADGE_ID
 LEFT JOIN MEORIENTB2B_PRD.EM_BUYER_BADGE bb ON bb.BADGE_ID = ebl.BADGE_ID
 LEFT JOIN MEORIENTB2B_PRD.em_exhibition EM ON ebl.EXHIBITION_ID = EM.id 
 LEFT JOIN MEORIENTB2B_PRD.SYS_WEBSITE_COUNTRY swc on EM.COUNTRY_ID=swc.COUNTRY_ID
 LEFT JOIN MEORIENTB2B_PRD.PCM_PURCHASE_INTERESTED_TAG PPIT ON PPIT.PURCHASER_ID=BB.PURCHASER_ID  and PPIT.WEBSITE_ID=swc.WEBSITE_ID

WHERE
 EM.year = 2019 
 AND EM.period IN ( 'Q1' ) 
 AND (
  ( EBL.ACTION_TYPE IN ( 'CheckIn' ) AND EBI.BADGE_TYPE_ID IN ( '0007' ) ) 
  OR ( EBL.ACTION_TYPE IN ( 'CheckIn' ) AND EBI.BADGE_TYPE_ID IN ( '0006', '0009' ) ) 
 ) 
 AND  EBL.ACTION_TIME  >TO_DATE('2019-06-05 04:37:17', 'yyyy-MM-dd hh24:mi:ss')  AND  EBL.ACTION_TIME <= TO_DATE( '2019-06-05 05:37:17', 'yyyy-MM-dd hh24:mi:ss' ) 
 
 AND PPIT.TAG_CODE is not NULL

