

CREATE    TABLE    MEORIENTB2B_BI.A_PRODUCER_MATCH_DEMO( 
	WEBSITE_ID  VARCHAR(50),
	PURCHASER_ID VARCHAR(50),
	SUPPLIER_ID VARCHAR(50),
	MATCH_SCORE  FLOAT,
	TAG_CODE VARCHAR(50),
	TAG_NAME VARCHAR(100),
	ACTION_TIME  DATE,
	OP_TIME NUMERIC,
	CREATE_TIME  DATE,
	SOURCE VARCHAR(50)
			)